# docker run --rm --label=jekyll --volume=D:\dev\spy-spotify\:/srv/jekyll  -it -p 4000:4000 jekyll/jekyll jekyll serve --trace --force_polling
title: Spytify
description: Records Spotify to mp3 without ads while it plays and includes media tags to the recorded files
show_downloads: true
url: https://jwallet.github.io/spy-spotify/
download: https://www.github.com/jwallet/spy-spotify/releases/latest
logo: https://raw.githubusercontent.com/jwallet/spy-spotify/master/psd/logo.png
languages: ['en', 'fr']
defaultLang: en
exclude_from_localizations: ['assets', '_sass', 'EspionSpotify', 'EspionSpotify.Tests', 'packages', 'psd', 'EspionSpotify.sln']
languageNames:
  fr: Fran√ßais
  en: English
collections:
  faq:
    output: true
sass:
  sass_dir: _sass