theme: jekyll-theme-cayman
title: Spytify
show_downloads: true
download: https://www.github.com/jwallet/spy-spotify/releases/latest
logo: https://raw.githubusercontent.com/jwallet/spy-spotify/master/psd/logo.png